### ISSUE TITLE
Initial Load takes almost 20-25+ minutes

### ISSUE THREAD

**Issue by sureshfizzy** [jellyflix-app/jellyflix#32] opened 2024-02-04 12:11 UTC
My collection is almost full of 30+ TB files and is continually increasing. I tested the release apk and discovered that greater the library, the longer it took to load (20-25 mins in my case). After Initial loading, if i switch from any other menu to Home Page it will take the same amount of time to load back. I understand there were still many things to be done, I'm just letting you know about this issue.  Great work between.

**Comment by jdk-21** [comment] 2024-02-04 13:09
Thank you for your feedback. Yes, the Home Page isn't optimised yet. The library view probably suffers similar issues. 
Does this issue occur on every startup? Normally you should be able to scroll on the home page even when it's loading. Are there particular carousels that have longer loading times than others? 
My library is still very small, so I can't verify your issues on my end yet.

**Comment by sureshfizzy** [comment] 2024-02-04 13:59
Yes it occurs on every startup. I can give access to my library if needed for testing.

**Comment by jdk-21** [comment] 2024-02-05 14:49
Could you provide some screenshots? And do you encounter any issues on the Library View?
You can also contact me via Matrix: @jdk-21:matrix.org

**Comment by jdk-21** [comment] 2024-02-09 15:28
The latest commits (8841ae2) in the development branch should fix the loading time issue. The loading times increased with each additional library. 
Additionaly this commit should fix client crashes on older devices caused by the OS force closing the app to prevent great memory usage.

**Comment by sureshfizzy** [comment] 2024-02-09 15:51
> The latest commits ([8841ae2](https://github.com/jellyflix-app/jellyflix/commit/8841ae273da3401694e61a990487b13b49e81241)) in the development branch should fix the loading time issue. The loading times increased with each additional library. Additionaly this commit should fix client crashes on older devices caused by the OS force closing the app to prevent great memory usage.

I've tried the new build from dev branch and it seems promising now. Thanks for looking into this so quick.

**Closed** 2024-02-09 15:55 UTC
